server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL:http://localhost:8761/eureka}


userRegistrationUrl: http://localhost:9000/register-user