spring:
  config:
    activate:
      on-profile: test

  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create-drop
      
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL:http://localhost:8761/eureka}
