server:
  port: 8888

spring:
  cloud:
    gateway:
      routes[0]:
        uri: lb://users-service
        predicates: Path=/users-service/**
        filters: StripPrefix=1
  #      routes[1]:
  #        uri: lb://auth-service
  #        predicates: Path=/auth-service/**
  #        filters: StripPrefix=1
