server:
  port 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL:http://localhost:8761/eureka}